### PR TITLE
async-multipart: impl Stream for Multipart<Bytes>

### PR DESCRIPTION
**Pull request by shikhar**
This allows for zero-copy when using hyper with https://docs.rs/hyper/0.14.10/hyper/struct.Body.html#method.wrap_stream

### CODE REVIEW

**Comment by Jake-Shadle** [comment]
Apologies, forgot about this PR, will take a look now!

**Comment by shikhar** [comment]
Looks like the set of lints needs an upgrade from v0.3 to v0.4 https://github.com/EmbarkStudios/rust-ecosystem/issues/59

**Comment by Jake-Shadle** [comment]
Yes, I've just pushed that, just need a rebase and this PR should be good.

**Review by Jake-Shadle — APPROVED** [review]
Thanks for the PR, sorry it took so long to look at it!

**Comment by Jake-Shadle** [comment]
So I realized that after I merged this that this change doesn't actually affect usage of the Multipart stream, as they are only ever sent, not received, which is what the `Stream` impl is for. I don't think it has a negative impact on the library so I don't think there is any harm in keeping it, and I'll add it to the CHANGELOG, but don't think this change alone warrants a release. Unless I have missed something?

**Comment by shikhar** [comment]
Hey @Jake-Shadle I'm fine with no imminent release for this, since I'm able to use a git dependency.

> So I realized that after I merged this that this change doesn't actually affect usage of the Multipart stream, as they are only ever sent, not received, which is what the `Stream` impl is for.

Hmm, I am indeed using this new impl for sending. I have in-memory data to be uploaded and when I call `Object::insert_multipart()` with `content: Bytes`, I get `Multipart<Bytes>`. In order to create a hyper `Body`, without this change the only way to get the multipart body out is to rely on the `Read` / `AsyncRead` impls which involve copying, but the underlying data is all represented as `Bytes` so having this `Stream` impl avoids copying. With hyper it is especially convenient since I am able to use https://docs.rs/hyper/0.14.12/hyper/struct.Body.html#method.wrap_stream

**Comment by Jake-Shadle** [comment]
Ahh ok, thanks for clarifying, I just glanced at the docs which seem to say the inverse.

**Pull request merged**
